# 1. Utiliser une image Python légère officielle
FROM python:3.9-slim

# 2. Définir le dossier de travail dans le conteneur
WORKDIR /app

# 3. Copier les fichiers de dépendances en premier (pour optimiser le cache Docker)
COPY requirements.txt .

# 4. Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copier tout le reste du code (script + data + tests) dans le conteneur
COPY . .

# 6. Commande par défaut : Lancer le script de nettoyage
CMD ["python", "data_preprocessing.py"]